In [1]:
import numpy as np

In [2]:
arr=np.random.randint(1,10,size=(5,5))
arr

array([[3, 5, 4, 8, 5],
       [3, 6, 9, 5, 7],
       [9, 1, 7, 5, 3],
       [1, 6, 6, 8, 6],
       [5, 9, 2, 3, 6]])

## 전치

In [3]:
#전치1
arr.T

array([[3, 3, 9, 1, 5],
       [5, 6, 1, 6, 9],
       [4, 9, 7, 6, 2],
       [8, 5, 5, 8, 3],
       [5, 7, 3, 6, 6]])

In [4]:
#전치2 
np.transpose(arr)

array([[3, 3, 9, 1, 5],
       [5, 6, 1, 6, 9],
       [4, 9, 7, 6, 2],
       [8, 5, 5, 8, 3],
       [5, 7, 3, 6, 6]])

## dot

In [5]:
#행렬곱, 내적
np.dot(arr.T,arr)

array([[125,  93, 118, 107,  99],
       [ 93, 179, 135, 150, 160],
       [118, 135, 186, 166, 152],
       [107, 150, 166, 187, 156],
       [ 99, 160, 152, 156, 155]])

In [6]:
a = np.arange(6).reshape(2,3)
print(a,'\n')

y=np.swapaxes(a,0,1)  # 0은 2차원(열), 1은 1차원(행)
print(y,'\n')
y=a.T
print(y,'\n')
y=np.transpose(a)
print(y,'\n')

[[0 1 2]
 [3 4 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]] 

[[0 3]
 [1 4]
 [2 5]] 



In [7]:
# 1 ~ 100을 아래와 같이 출력하세요
[[  1   2   3   4   5   6   7   8   9  10]
 [ 20  19  18  17  16  15  14  13  12  11]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 40  39  38  37  36  35  34  33  32  31]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 60  59  58  57  56  55  54  53  52  51]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 80  79  78  77  76  75  74  73  72  71]
 [ 81  82  83  84  85  86  87  88  89  90]
 [100  99  98  97  96  95  94  93  92  91]] <class 'numpy.ndarray'>


SyntaxError: invalid syntax (Temp/ipykernel_18612/1317794496.py, line 2)

In [ ]:
arr=np.arange(1,101).reshape(10,10)
for i in range(10):
    if i%2==0:
        continue
    else:
        arr[i]=arr[i][::-1]
arr

In [ ]:

arr = np.arange(1,101).reshape(10,10)
for i in range(1,10):
    if i % 2 == 1:
        arr[i] = arr[i][::-1]
print(arr, type(arr))


In [ ]:
np.arange(1,101).reshape(10,10)
for i in range(10):
    if i%2==1:
        ar[i] = ar[i,::-1]
print(ar,type(ar))

arr = np.arange(1,101).reshape(10,10)
arr[[1,3,5,7,9]] = arr[[1,3,5,7,9]][:,[9,8,7,6,5,4,3,2,1,0]]
print(arr)


## 차원 변경( transpose )

In [ ]:
#(0,1,2)  3차원,2차원,1차원
# 3차원과 2차원을 바꾸는 경우 : (1,2,3) -> (2,1,3)
a=np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y = np.transpose(a,(1,0,2))
print(y,y.shape)

In [ ]:
# (1,2,3)->(2,3,1)
a=np.arange(6).reshape(1,2,3)
print(a,a.shape,'\n')

y=np.transpose(a,(1,2,0))
print(y,y.shape)

In [ ]:
#[과제]아래 배열에서 3차원과 2차원을 변경하여 출력하세요(shape 확인)
arr=np.arange(16).reshape(2,2,4)
print(arr,arr.shape,'\n')
y=np.transpose(arr,(1,0,2))
print(y,y.shape)

In [ ]:
#[과제] 상기 과제의 arr에서 2차원과 1차원을 변경하여 출력하세요.
import numpy as np
arr=np.arange(16).reshape(2,2,4)
arr21=np.transpose(arr,(0,2,1))
print(arr21,arr21.shape,'\n')
arrs=arr.swapaxes(1,2)
print(arrs,arrs.shape)

In [ ]:
z=np.transpose(y,(0,2,1))
print(z.swapaxes(1,2),z.shape)

## mod, remainder 나머지 함수

In [ ]:
#나머지를 구할 경우 사용하는 함수
value1 = np.array([15,30,45])
value2 = np.array([2,7,9])
print(np.mod(value1,value2))
print(np.add(value1,value2))
print(np.remainder(value1,value2))
print(np.multiply(value1,value2))
print(np.subtract(value1,value2))

## reciprocal - 역수

In [8]:
# 각 수의 역수를 구해주는 함수 reciprocal(역수)
value = np.array([0.85,1.85,1,100])
print(np.reciprocal(value),'\n')
value1=np.array([100],dtype=int)
print(np.reciprocal(value1,dtype=float))

[1.17647059 0.54054054 1.         0.01      ] 

[0.01]


## power - 승수

In [9]:
#승수의 결과 값을 표시해주는 함수
value1 = np.array([2,10,15])
value2 = np.array([1,2,3])
print(np.power(value1,2),'\n')
print(np.power(value1,value2))


[  4 100 225] 

[   2  100 3375]


In [10]:
arr=np.random.randn(10)
print(arr,'\n')
print(arr.mean(),'\n')
print(arr.std())

[ 0.49564221 -2.03483669  0.17046017 -0.53314212 -0.27650498  1.36237497
 -0.32123321 -0.56943318  0.13759515 -0.26660142] 

-0.18356790875220497 

0.8253799845841905


In [ ]:
#양수인 원소의 개수
(arr>0).sum()

In [ ]:
#하나 이상의 값이 True인지 검사
bools = np.array([False,False,True,True])
bools.any()

In [ ]:
#모든 원소가 True인지 검사
bools.all()

In [ ]:
# 삼항식의 백터와 버전
arr=np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, -2)

In [ ]:
# arr의 모든 양수를 2로 바꿀 경우
arr=np.random.randn(4,4)
print(arr,'\n')
np.where(arr > 0, 2, arr)

In [ ]:
# 두개의 1차원 배열을 받아서 가능한 모든 (X,Y) 짝을 만들 수 있는 2차원 배열 2개 반환 meshgrid함수
x=np.arange(1,4)
y=np.arange(1,4)
xs,ys= np.meshgrid(x,y)
print(xs,'\n\n',ys)

In [ ]:
# np.sort 원본 반영되지 않음.
np.random.seed(0)
arr=np.random.randint(1,100,size=10)
print(arr,'\n')
print(np.sort(arr),'\n')
print(arr)

In [ ]:
sorted = np.sort(arr)
print(sorted)

In [ ]:
# 행렬이 2차원 이상일 때 axis 축 값 설정을 통해 행, 열 방향으로 정렬 수행
arr2d=np.array([[8,12],[7,1]])
print(arr2d,'\n')
sort_ar2d_axis0=np.sort(arr2d,axis=0) #행방향
print(sort_ar2d_axis0,'\n')
sort_ar2d_axis0=np.sort(arr2d,axis=1) #열방향
print(sort_ar2d_axis0)

In [ ]:
# ndarray.sort() : 원본 반영
np.random.seed(0)
arr=np.random.randint(1,10,size=10)
print(arr,'\n')
arr.sort() #원본 반영
arr

In [ ]:
# 다차원 배열의 정렬은 sort 메소드에 넘긴 축에 따라 1차원 부분을 정렬
#열방향 default
np.random.seed(0)
arr=np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort(1)
print(arr,'\n')
arr.sort(0)
print(arr,'\n')

In [ ]:
#열방향 정렬
np.random.seed(0)
arr=np.random.randint(1,10,size=(5,3))
print(arr,'\n')
arr.sort()
print(arr)

In [ ]:
# 정렬된 행렬의 인덱스 반환 : 기존 원본 행렬의 원소에 대한 인덱스를 필요로 할 때
org_array = np.array([3,1,9,5])
sort_indices = np.argsort(org_array)
print(org_array)
print(sort_indices)
sort_indices # 인덱스 반환    1-1 3-0 5-3 9-2

In [ ]:
# 배열에서 정렬한 후 5% 분위수에 해당하는 원소만 출력
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]



In [ ]:
# 배열 집합 연산
names = np.array(['Bob','Joe','Will','Joe','Joe'])
np.unique(names)

In [ ]:
import numpy as np
names = np.array(['Bob','Joe','Will','Joe','Joe'])
sorted(set(names))

In [ ]:
# 첫번째 배열의 원소가 두번째 배열의 원소를 포함하는지 알려주는 불리언 배열을 반환
values = np.array([6,0,0,3,2,5,6])
np.in1d(values,[2,3,6])

In [ ]:
# 배열 데이터의 입출력
# np.save, np.load는 바이너리 형식 .npy 파일로 저장
arr=np.arange(10)
np.save('some_array',arr)

In [ ]:
np.load('some_array.npy')

In [ ]:
# np.savez : 여러개의 배열을 압축된 형식으로 저장
np.savez('array_archive.npz',a=arr,b=arr)

In [13]:
arch = np.load('array_archive.npz')
print(arch['b'])
print(arch['a'])

[0 1 2 3 4 5 6 7 8 9]
[0 1 2 3 4 5 6 7 8 9]


In [ ]:
# Q. 인덱싱을 사용하여 [1 0 1 0 1 0 1 0 1 0] 을 출력하세요.
a = np.ones(10)
a[[1,3,5,7,9]] = 0
print(a)

In [ ]:
# Q. a = np.arange(10)에서 [6,7,8,9] 출력
a = np.arange(10)  # 6,7,8,9 출력
a[a>5]


In [ ]:
# Q. a에서 최대값, 최소값의 인덱스 출력
a=np.arange(1,10)
print(np.argmax(a))
print(np.argmin(a))


In [12]:
# Q. a에서 인덱스 배열을 역순으로 출력하세요.
np.argsort(a)[::-1]   # 인텍스 -> arg~

array([[0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [ ]:
# Q. np.ones((10,10))을 아래와 같이 출력하세요.
array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [ ]:
ar=np.ones((10,10))
ar[1:9,1:9] = 0
print(ar)

In [ ]:
# [과제] np.ones((5,5))을 아래와 같이 출력하세요.
array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
ar=np.ones((10,10))
ar[[0,1,8,9]]=0 #행 
ar[:,[0,1,8,9]]=0 #열
print(ar)

In [ ]:
a=np.ones((5,5))
b=np.zeros((9,9))
b[2:7,2:7]=a
b

In [11]:
arr1 = np.ones((5,5))
np.pad(arr1,(2,2),'constant',constant_values=0)

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 1., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [ ]:
# [과제] np.zeros((8,8))을 이용해서 아래와 같이 출력하세요(두가지 방식:인덱싱, tile함수)
array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [ ]:
arr=np.zeros((8,8),dtype=int)
arr[::2,1::2]=1
arr[1::2,::2]=1
arr

In [ ]:
a=np.array([[0,1],[1,0]])
b=np.tile(a,(4,4))
print(b)

In [ ]:
arr=np.zeros((8,8),dtype=int)

In [ ]:
# [도전과제] np.arange(336).reshape(6,7,8)에서 100번째 요소의 인덱스를 구하세요

In [ ]:
arr=np.arange(336).reshape(6,7,8)
print(np.where(arr==99),'\n')

arr = np.arange(336).reshape(6,7,8)
print(arr)
print(np.unravel_index(99,(6,7,8)))  # 인덱스 검출


In [ ]:
large_arr = np.random.randn(1000)
large_arr.sort()
large_arr[int(0.05*len(large_arr))]

In [ ]:
# [도전과제] np.arange(4)을 이용해서 아래와 같이 출력하세요.
array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

In [ ]:
arr=np.arange(4)
np.diag(arr+1,k=-1)

In [ ]:
zero = np.zeros((5, 5))
a = np.arange(4)

for i in range(4):
    zero[i + 1, i] = a[i] + 1
    
print(zero)


In [ ]:
arr=np.arange(1,5)
array=np.zeros((5,5))
# array[1:5,0:5] = arr[1,2,3,4]
array
arr

[파이썬 random 함수]


In [ ]:
import random
print(random.random(),'\n') # 0.0 <= x < 1.0
print(random.randint(1,10),'\n') # 1 <= x < 10 난수 값 리턴
print(random.uniform(10,20),'\n') # min <= x < max float리턴
print(random.randrange(10),'\n') # 0<= x <10 int 리턴
print(random.choice([1,2,3,4,5]),'\n') # 리스트 내부에 있는 요소를 랜덤하게 선택
li=[1,2,3,4,5]
print(random.sample(li,3),'\n')  # 리스트 요소를 중복이 안되게  리턴
random.shuffle(li)
print(li)

[numpy random 함수]

- np.random.seed : seed를 통한 난수 생성
- np.random.randint : 균일분포의 정수 난수 1개 생성
- np.random.rand : 0부터 1사이의 균일분포에서 난수 매트릭스 배열 생성
- np.random.randn : 가우시안 표준 정규분포에서 난수 매트릭스 배열 생성
- np.random.shuffle : 기존의 데이터 순서 바꾸기
- np.random.choice : 기존 데이터에서 sampling

In [ ]:
print(np.random.randint(6),'\n') # 0~5 까지 정수인 난수 1개
print(np.random.randint(1,20),'\n') # 1~19 까지 정수인 난수 1개
print(np.random.randint(10,size=10),'\n') # 0~9까지 정수인 난수 10개
print(np.random.randint(10,20,size=10),'\n') #10~19 까지 정수인 난수 10개
print(np.random.randint(10,20,size=(3,5)),'\n') # 10~19까지 정수인 난수 3행 5열 배열생성

In [ ]:
r=np.random.rand(6) # 0~1사이의 균일분포
print(r)
r.mean()

In [ ]:
#표준 정규분포
r = np.random.randn(6)
print(r)
r.mean()

In [ ]:
import random as np
list = np.random.arange(1,6)
print(list,'\n')
np.random.shuffle(list)
list

In [ ]:
np.random.choice(list,5)

In [ ]:
a = np.array([11,11,3,3,2,2,2,7])
index,count=np.unique(a,return_counts=True)
print(index)
print(count)

In [ ]:
np.random.uniform(1.0,2.0,10)

In [ ]:
np.random.uniform(0,1,(2,3))

In [ ]:
# 0 ~ 1 사이의 실수값으루 행렬 생성
# uniform 함수의 최소값, 최대값을 각각 0,1로 지정한 것과 같음
np.random.random_sample((2,3))

In [ ]:
!pip install pandas

In [ ]:
ar=np.random.rand(4,8)
ar

In [ ]:
# 배얄을 데이터프레임으로 변환
import pandas as pd
df = pd.DataFrame(ar)
print(df,type(df))
df

In [ ]:
print(df[0])
type(df[0])

In [ ]:
columns = ['id','gender','age','region','product','price','qty','time']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
df

In [ ]:
# 의미있는값으로 변환하여 3개의 컬럼으로 구성된 df를 출력하세요,
ar=np.zeros((4,3))
columns = ['id','gender','age']
index = [np.arange(4)]
df = pd.DataFrame(ar,index,columns=columns)
np.random.seed(0)
df.id=np.arange(1,5)
df.gender=np.random.randint(0,2,4)
df.age=np.arange(1,5)*10
df

[과제] 아래 가이드에 따라서 고객 구매데이터를 생성하고 데이터프레임으로 변환하여 출력하세요(관측치 1000개)

- id : 1 ~ 1000번 일련번호
- gender : 0,1 정수 난수 생성
- age : 0 ~ 80사이 정수 난수 생성
- region : 1 ~ 10 사이 정수 난수 생성
- product_19 : 제품코드 11111 ~ 99999
- product_20 : 제품코드 11111 ~ 99999
- price_19 : 1000 ~ 50000 사이 실수 난수 생성
- price_20 : 1000 ~ 50000 사이 실수 난수 생성
- quantity_19 : 1 ~ 100 사이 정수 난수 생성
- quantity_20 : 1 ~ 100 사이 정수 난수 생성
- time_19 : 01 ~ 24 사이 정수 난수 생성
- time_20 : 01 ~ 24 사이 정수 난수 생성
- amount_19 : price_19 * quantity_19
- amount_20 : price_20 * quantity_20
- sales : 19년 대비 20년구매금액이 증가면 1, 감소면 0

In [ ]:
import pandas as pd
import numpy as np
ar = np.zeros((1000,15))
columns = ['id','gender','age','region','product_19','product_20','price_19',
           'price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales']
index = [np.arange(1000)]
df = pd.DataFrame(ar,index,columns=columns)
df.id = np.arange(1,1001)
df.gender=np.random.choice(['M','F'],1000)
df.age=np.random.randint(0,80,1000)
df.region=np.random.randint(1,10,1000)
df.product_19=np.random.randint(111,222,1000)
df.product_20=np.random.randint(111,999,1000)

for i in range(1,1001)
    df.price_19[i]=np.random.randint(1000,50000)
    df.price_20[i]=np.random.randint(1000,50000)

df.quantity_19=np.random.randint(1,100,1000)
df.quantity_20=np.random.randint(1,100,1000)
df.time_19=np.random.randint(0,24,1000)
df.time_20=np.random.randint(0,24,1000)
df.amount_19=df.price_19*df.quantity_19
df.amount_20=df.price_20*df.quantity_20
df.loc[df.amount_20 > df.amount_19,'sales'] = '1'
# df.loc[df.amount_20 == df.amount_19,'sales'] = '-'
df.loc[df.amount_20 < df.amount_19,'sales'] = '0'
# df.sales=np.where(df.amount_20-df.amount_19>0,1,0)
df
# condition = (df.sales == '1') 
# df[condition]

In [ ]:
df[df.product_19==111]

In [ ]:
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings(action='ignore') 
customer = 1000

array = np.zeros((customer,14),dtype = int)
df = pd.DataFrame(array,(np.arange(1,customer+1)),columns = ['id','gender','age','product_19','product_20','price_19','price_20','quantity_19','quantity_20','time_19','time_20','amount_19','amount_20','sales'])
np.random.seed(0)
df.id = np.arange(1,customer+1)
df.gender = np.random.choice(['M','F'],customer)
df.age = np.random.randint(1,81,size=customer)
df.product_19 = np.random.randint(111,222,size = customer)
df.product_20 = np.random.randint(111,222,size = customer)

pricearray= np.random.randint(10,500,size = 100000)*100
print(pricearray)
for i in range(1,customer+1):
    df.price_19[i] = pricearray[df.product_19[i]]
    df.price_20[i] = pricearray[df.product_20[i]]

df.quantity_19 = np.random.randint(1,101,size = customer)
df.quantity_20 = np.random.randint(1,101,size = customer)

df.time_19 = np.random.randint(1,25,size = customer)
df.time_20 = np.random.randint(1,25,size = customer)

df.amount_19 = df.price_19*df.quantity_19
df.amount_20 = df.price_20*df.quantity_20

for i in range(1,customer+1):
    if df.amount_20[i]>df.amount_19[i]:
        df.sales[i] = 1
    else:
        df.sales[i] = 0

print(df.shape)
df.head()

In [ ]:
df[df.sales==0]

In [ ]:
df[df.product_19==220]