## Numpy
Numpy는 "Numerical"의 약자로 대규모 다차원 배열과 행렬 연산에 필요한 다양한 함수를 제공
- Numerucal Python을 의미하는 Numpy는 파이썬에서 선형대수 기반의 프로그램을 쉽게 만들 수 있도록 지원하는 대표적인 패키지
- 많은 머신러닝 알고리즘이 넘파이 기반으로 작성되어 있으며 알고리즘의 입출력 데이터를 넘파이 배열 타입으로 사용함
- 넘파이의 기본 게이터 타입은 ndarray.ndarray를 이용해 넘파이에서 다타원 배열을 쉅게 생성하고 다양한 연산 수행
 
Numpy 특징
- 강력한 N차원 배열 객체
- 정교한 브로드케스팅 기능
- 유용한 선형 대수학, 푸리에 변환 및 난수 기능
- 퓨리에 변환은 시간이나 공간에 대한 함수를 시간 또는 공간 주파수 성분으로 분해하는 변환
- 범용적 데이터 처리에 사용 가능한 다차원 컨테이너

In [1]:
!pip install numpy

### arnage

In [7]:
import numpy as np
z=np.arange(10) #1에서 10까지 1차원 배열
print(z,type(z))

[0 1 2 3 4 5 6 7 8 9] <class 'numpy.ndarray'>


In [71]:
my_arr = np.array(1000000)
my_list = list(range(1000000))

1000000


In [12]:
%time for _ in range(10):my_array2=my_arr*2
print(my_array2)

Wall time: 0 ns
2000000


In [11]:
%time for _ in range(10) : my_list2=[x*2 for x in my_list]

Wall time: 1.27 s


### randn(표준정규분포)

In [18]:
#배열 연산     #2*3행렬  
#np.random.randn 가우시안 표준 정규뷴표에서 난수 매트릭스 array생성
data=np.random.randn(2,3)
print(data,'\n')
print(data*10,'\n')
print(data+data)


[[-1.183432    0.52244863  0.24705797]
 [ 0.06328124 -2.09323847  0.70155051]] 

[[-11.83432004   5.22448627   2.47057971]
 [  0.63281242 -20.93238467   7.01550513]] 

[[-2.36686401  1.04489725  0.49411594]
 [ 0.12656248 -4.18647693  1.40310103]]


In [19]:
print(data.shape) # 크기
print(data.dtype) # 데이터타입
print(data.ndim) #차원

(2, 3)
float64
2


In [27]:
data=np.random.randn(2,2,4)
data
print(data)

[[[ 0.73115968 -1.65099565 -1.19800305  0.43176969]
  [ 0.43332613  0.09384696 -2.68830335  0.77840764]]

 [[-1.05435622 -1.36969167 -0.37837638 -0.58885584]
  [-1.70886459  1.19641464 -0.22797532 -0.27843458]]]


### ndim(차원) , shape(크기) ,dtype(데이터 타입)

In [21]:
print(data.shape) # 크기
print(data.dtype) # 데이터타입
print(data.ndim) # 차원

(2, 3, 4)
float64
3


 다차원 배열
 
<img src = 'numpy차원.jpg' STYLE='width:200px;'>

In [35]:
data2=[[1,2,3,4],[5,6,7,8]]
print(type(data2))
arr2 = np.array(data2)
print(arr2,type(arr2))

<class 'list'>
[[1 2 3 4]
 [5 6 7 8]] <class 'numpy.ndarray'>


In [38]:
print(arr2.ndim,'\n')
print(arr2.shape)

2 

(2, 4)


In [41]:
# 1차원 배열로 3개의 데이터
array1 = np.array([1,2,3])
print(array1,type(array1)) 
print(array1.ndim,'\n')
print(array1.shape) #(,열)이 아닌 (열,) 형태로 출력

[1 2 3] <class 'numpy.ndarray'>
1 

(3,)


In [51]:
#2차원 배열로 2개의 row와 3개의 colum으로 구성된 6개의 데이터
array2=np.array([[1,2,3],
                 [4,5,6]])
print(array2.ndim)
# print(array2.shape)
# print(array2)
print(array2,type(array2),array2.shape)

2
[[1 2 3]
 [4 5 6]] <class 'numpy.ndarray'> (2, 3)


In [52]:
#1개의ㅣrow와 3개의 colum으로 구성된 2차원 배열
array3=np.array([[1,2,3]])
print(array3.ndim)
# print(array3.shape)
# print(array3)
print(array3,type(array3),array3.shape)

2
[[1 2 3]] <class 'numpy.ndarray'> (1, 3)


In [60]:
array4=np.array([[[1,2,3],[4,5,6]],
                 [[4,5,6],[7,8,9]]],dtype=object)
print(array4.ndim)
# print(array3.shape)
# print(array3)
print(array4,type(array4),array4.shape)

# 차원 행 렬 (2,2,3)

3
[[[1 2 3]
  [4 5 6]]

 [[4 5 6]
  [7 8 9]]] <class 'numpy.ndarray'> (2, 2, 3)


In [61]:
# 경고 메세지 처리
import warnings
warnings.filterwarnings('ignore')

## 배열 생성 및 초기화
- Numpy 는 원하는 shape로 배열을 설정하고 각 요소를 특정 값으로 초기화 하는 zeros, ones, full, eye 함수 제공
- 파라미터로 입력한 배열과 같은 shape의 배열을 만드는 zeros_like, ones_like, full_like 함수도 제공

### zeros

In [78]:
print(np.zeros(10),'\n')
print(np.zeros((3,6)),'\n')
print(np.zeros((2,3,2)),'\n')

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] 

[[0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]] 

[[[0. 0.]
  [0. 0.]
  [0. 0.]]

 [[0. 0.]
  [0. 0.]
  [0. 0.]]] 



### ones

In [76]:
print(np.ones(10),'\n')
print(np.ones((3,6)),'\n')
print(np.ones((2,3,2),'\n'))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.] 

[[1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1.]] 

[[[1 1]
  [1 1]
  [1 1]]

 [[1 1]
  [1 1]
  [1 1]]]


### full

In [81]:
ar1=np.full((2,2),7)
ar1


array([[7, 7],
       [7, 7]])

### eye(단위행렬)

In [84]:
#항등행렬, 단위행렬
ar2=np.eye(3)
ar2

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### zeros_like, ones_like, full_like

In [21]:
# [과제] zeros_like, ones_like, full_like 함수 사용 예를 작성하세요.
array=([[0, 1, 2],
       [3, 4, 5]])
array1=np.zeros_like(array)
print(array1,'\n')
array2=np.ones_like(array)
print(array2,'\n')
array3=np.full_like(array,5)
print(array3,'\n')

[[0 0 0]
 [0 0 0]] 

[[1 1 1]
 [1 1 1]] 

[[5 5 5]
 [5 5 5]] 



In [86]:
#arange 함수 : python의 range함수의 배열 버전
arr1=np.arange(15)
arr1
arr2=range(15)
arr2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [90]:
arr2=arr1.reshape(3,5)
print(arr2)
arr3=arr1.reshape(1,3,5)
print(arr3,arr3.shape)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]] (1, 3, 5)


### reshape(재배열)

In [94]:
# array1에 reshape 함수를 이용, (5,2) 배열을 생성하고 크기를 같이 출력하세요
arry1 = np.arange(10)
arry2 = arry1.reshape(5,2)
print(arry2)
arry3 = np.zeros_like(arry2)
print(arry3)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]
[[0 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


In [99]:
# 0-29 일차원 배열을 생성한 후 일차원 배열을 다시 2,3차원 배열을 생성하세요
arr=np.arange(30)
print(arr,'\n')
arr1=arr.reshape(3,10)
print(arr1,'\n')
arr2=arr.reshape(3,2,5)
print(arr2,'\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] 

[[ 0  1  2  3  4  5  6  7  8  9]
 [10 11 12 13 14 15 16 17 18 19]
 [20 21 22 23 24 25 26 27 28 29]] 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] 



### reshape(-1,-1)

In [5]:
#reshape(-1,-1)
array1 = np.arange(30)
ar12 = array1.reshape(5,-1)
print(ar12,ar12.shape,'\n')
ar13=array1.reshape(-1,2,5)
print(ar13,ar13.shape,'\n')

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]] (5, 6) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [6]:
ar14=ar12.reshape(-1,)
print(ar14,ar14.shape,'\n')
ar15=ar12.reshape(-1,2,5)
print(ar15,ar15.shape,'\n')

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29] (30,) 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]] (3, 2, 5) 



In [111]:
# ar15 -> 1,2
ar1=ar15.reshape(-1,)
print(ar1)
ar2=ar15.reshape(2,-1)
print(ar2)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


## 행렬의 종료

- 정방행렬 행과 열의 수가 같은 행렬
- 대각행렬은 주대각선 원소를 제외한 모든 원소들이 0인 정방행렬
- 항등행렬은 행렬 곱셈 연산에 항등원으로 작용하는 행렬
- 영행렬은 모든 원소가 0인 행렬로 곱셈 연산에서 영원으로 작용하는 행렬
- 전치행렬은 주대각선 원소를 기준으로 행과 열을 바꿔주는 행렬
- 직교행렬은 행렬 A의 역행렬이 A의 전치행렬이고 A의 전치행렬과 A 행렬을 곱하였을 때 항등행렬이 나오는 행렬

### 정방행렬

In [117]:
arry1=np.eye(5)
print(arry1)
arry2=np.full((5,5),7)
print(arry2)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


### 항등행렬, 단위행렬

In [118]:
a=np.eye(5)
a

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### 영행렬

In [122]:
a=np.zeros(25)
a.reshape(5,5)

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

## ndarray 데이터 형태 지정 및 변경
<img src = '데이터형태.jpg' STYLE='width:200px;'>

In [126]:
arr1=np.array([1,2,3],dtype=np.float64)
arr2=np.array([1,2,3],dtype=np.int32)
print(arr1,arr1.dtype)
print(arr2,arr2.dtype)

[1. 2. 3.] float64
[1 2 3] int32


### 데이터 변경

In [129]:
arr=np.array([1,2,3,4,5])
print(arr.dtype)
float_arr=arr.astype(np.float64)
print(float_arr.dtype)

int32
float64


In [131]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [132]:
# empty 함수 : shape와 dtype을 입력 받아 초기화되지 않은 배열을 만들어준다 cf,zeros함수
# empty 함수를 수행할 때마다 값이 다른 것을 확인할수 있다. 이는 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이
# 그대로 영역의 주소만 알려줄 뿐 초기화는 사용자에게 맡기기 떄문임..
print(np.empty(shape=(10,),dtype=np.int8))

[1 1 1 1 1 1 1 1 1 1]


### 문자열로 배열 생성

In [146]:
# arr=np.array([1,2,3,4],dtype='S')
arr=np.array([1,2,3,4],dtype=np.string_)
print(arr,arr.dtype)
print(arr[0])

[b'1' b'2' b'3' b'4'] |S1
b'1'


In [137]:
arr.astype(float)
print(arr1,arr1.dtype)

[1. 2. 3.] float64


In [159]:
## 정수와 실수로 구성된 list_e=[1.2,2.3,3]을 numpy를 이용해서 실수형과 정수령으로 각각 출력하세요.
list_e=[1.2,2.3,3]
array_e1 = np.array(list_e)
print(array_e1,array_e1.dtype)
arrey_e2=array_e1.astype(np.int64)
print(arrey_e2,arrey_e2.dtype)

[1.2 2.3 3. ] float64
[1 2 3] int64


### 배열의 산술 연산

In [163]:
#배열의 산술 연산
arr = np.array([[1,2,3],[4,5,6]])
arr = np.arange(1,7).reshape(2,3)
print(arr,arr.dtype)

[[1 2 3]
 [4 5 6]] int32


In [164]:
arr*arr

array([[ 1,  4,  9],
       [16, 25, 36]])

In [171]:
arr2 = np.array([[0.,4.,1.],[7.,2.,12.]])
arr2

array([[ 0.,  4.,  1.],
       [ 7.,  2., 12.]])

In [172]:
arr2 > arr

array([[False,  True, False],
       [ True, False,  True]])

In [189]:
# 기본 사칙연산
value1 = np.arange(1,10).reshape(3,3)
value2 = np.arange(11,20).reshape(3,3)
print(value1,'\n\n',value2,'\n')
print(value1+value2,'\n')
print(np.add(value1,value2),'\n')
print(value2-value1,'\n')
print(np.subtract(value2,value1),'\n')
print(value1*value2,'\n')
print(np.multiply(value2,value1),'\n')
print(value2/value1,'\n')
print(np.divide(value2,value1),'\n')

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

 [[11 12 13]
 [14 15 16]
 [17 18 19]] 

[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[12 14 16]
 [18 20 22]
 [24 26 28]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[10 10 10]
 [10 10 10]
 [10 10 10]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[ 11  24  39]
 [ 56  75  96]
 [119 144 171]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]] 

[[11.          6.          4.33333333]
 [ 3.5         3.          2.66666667]
 [ 2.42857143  2.25        2.11111111]] 



In [196]:
arr=np.random.randn(2,2)
arr

array([[-1.59173378,  1.72974115],
       [-0.43643311,  0.26324521]])

In [198]:
arr.mean().round(4)  #평균함수

-0.0088

In [199]:
arr.mean(axis=1) #가로방형 렬방향

array([ 0.06900368, -0.08659395])

In [201]:
arr.mean(axis=0) #세로방향 행방향

array([-1.01408344,  0.99649318])

In [202]:
arr.sum().round(4)

-0.0352

### cumprod(누적 계산)

In [203]:
arr.cumprod()  #처음부터 누적하여 계산

array([-1.59173378, -2.75328741,  1.20162579,  0.31632224])

In [236]:
#인덱싱, 슬라이싱
arr2d = np.arange(1,10).reshape(3,3)
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [214]:
arr2d[2,2]
arr2d[2][2]

9

In [216]:
arr2d[::,0]

array([1, 4, 7])

In [241]:
arr2d = np.arange(1,10).reshape(3,3)
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [244]:
arr2d[[0,2],:]

array([[1, 2, 3],
       [7, 8, 9]])

In [229]:
#arr2d에서 [3,6]   [[1,2][4,5]]
print(arr2d[:2,2])
print(arr2d[:2,:2])

[3 6]
[[1 2]
 [4 5]]


In [247]:
arr = np.arange(30).reshape(5,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [ ]:
14 15 16
3 9 
1 7 13

In [270]:
print(arr[[2],2:5])
print(arr[[0,1],3])
print(arr[:3,1])


[[14 15 16]]
[3 9]
[ 1  7 13]


### 배열 -> 리스트

In [276]:
#배열을 리스트로 배열
li=arr.tolist()
print(li,type(li))

[[0, 1, 2, 3, 4, 5], [6, 7, 8, 9, 10, 11], [12, 13, 14, 15, 16, 17], [18, 19, 20, 21, 22, 23], [24, 25, 26, 27, 28, 29]] <class 'list'>


# 매우 중요함 boolean indexing

In [284]:
#Boolean indexing
arr1d = np.arange(1,10)
print(arr1d)
arr3 = arr1d[arr1d>5]
print(arr3)
print(arr1d > 5)

[1 2 3 4 5 6 7 8 9]
[6 7 8 9]
[False False False False False  True  True  True  True]


In [290]:
#arr1d에서 일반 인덱스를 이용해서  [6 7 8 9]를 출력하세요.
for i in range(len(arr1d)):
    if i > 4:
        print(arr1d[i],end=' ')

6 7 8 9 

In [288]:
arr1d[5:]

array([6, 7, 8, 9])

In [294]:
#1~14
array_e=np.arange(1,15)
array_f=array_e[(array_e/2) > 5]
array_f

array([11, 12, 13, 14])

In [1]:
names = np.array(['Bob','Joe','Will','Bob','Will','Joe','Joe'])
data=np.random.randn(7,4)
print(data)
print(names)
#0번째와 3번째 인텍스만 출력

[[-0.72945984  2.12372914 -0.04693569 -1.58912926]
 [ 2.26514137  0.19853757 -0.45041452 -1.3710655 ]
 [-0.2527519   0.23540038 -0.41256735 -0.26411488]
 [ 0.18214192 -0.04915001 -2.00880563 -0.56601671]
 [ 0.48069547  1.47471617  0.27191324  1.05229529]
 [-1.14803066 -0.9271606  -0.15536921  1.43697577]
 [-0.21960115  0.0183786   0.85606721  0.48082027]]
['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']


In [5]:
data[names=='Bob']

array([[-0.72945984,  2.12372914, -0.04693569, -1.58912926],
       [ 0.18214192, -0.04915001, -2.00880563, -0.56601671]])

In [303]:
data[names=='Bob',2:]

array([[ 1.33177652, -1.29843542],
       [ 1.05292584,  0.56912157]])

In [304]:
data[names !='Bob']

array([[ 0.19025041, -1.89120204,  1.79766062,  0.48402448],
       [-0.67376564, -0.26468218, -0.83736697,  1.06902133],
       [-0.96055003, -0.08777105,  2.25752946, -0.70479877],
       [ 0.01491834, -0.08622208, -1.19291177, -0.22317631],
       [ 0.0968054 , -0.23232003, -0.95833453,  0.98069468]])

In [323]:
mask = (names == 'Bob') | (names=='Will')
data[mask]

array([[-0.84413138, -0.45047046,  1.33177652, -1.29843542],
       [-0.67376564, -0.26468218, -0.83736697,  1.06902133],
       [-0.77367965, -1.19503031,  1.05292584,  0.56912157],
       [-0.96055003, -0.08777105,  2.25752946, -0.70479877]])

In [333]:
#음수를 모두 0으로 처리하여 출력
data[data<0]=0
data.round(2)

array([[0.  , 0.  , 1.33, 0.  ],
       [0.19, 0.  , 1.8 , 0.48],
       [0.  , 0.  , 0.  , 1.07],
       [0.  , 0.  , 1.05, 0.57],
       [0.  , 0.  , 2.26, 0.  ],
       [0.01, 0.  , 0.  , 0.  ],
       [0.1 , 0.  , 0.  , 0.98]])

#### 과제

In [26]:
# [과제] 1 ~ 100까지 정수에서 3의 배수인 것만을 출력(for문과 배열 두가지 방식)
array=np.arange(1,101)
array3=array[array%3==0]
print(array3)

[ 3  6  9 12 15 18 21 24 27 30 33 36 39 42 45 48 51 54 57 60 63 66 69 72
 75 78 81 84 87 90 93 96 99]


In [25]:
li=[]
for i in range(1,101):
    if i % 3==0:
        li.append(i)
print(li)
        

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48, 51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99]


In [6]:
# [과제] 1 ~ 100까지 정수에서 5의 배수이면서 2의 배수인 것만을 출력(for문과 배열 두가지 방식)
import numpy as np
array=np.arange(1,101)
array5=array[(array%5==0) & (array%2==0)]
array5

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [27]:
li=[]
for i in range(1,101):
    if i%5==0 and i%2==0:
        li.append(i)
print(li)

[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]


In [33]:
# [과제] 표준정규분포로 구성된 5행 5열 다차원 배열을 생성하고 함수를 이용하여 평균과 표준편차를 구하세요.
data=np.random.randn(5,5)
print(f'평균 : {data.mean()}')
print(f'표준편차 : {data.std()}') 

평균 : -0.023528195819214334
표준편차 : 1.0264880890383876


In [18]:
# [과제] 현재 사용하고 있는 numpy의 버전을 출력하세요.
np.__version__

'1.21.2'

In [351]:
# [과제] numpy 함수의 도움말 기능을 볼수 있는 방법을 수행하여 add 함수의 가이드를 출력하세요.
help(np.add)

Help on ufunc object:

add = class ufunc(builtins.object)
 |  Functions that operate element by element on whole arrays.
 |  
 |  To see the documentation for a specific ufunc, use `info`.  For
 |  example, ``np.info(np.sin)``.  Because ufuncs are written in C
 |  (for speed) and linked into Python with NumPy's ufunc facility,
 |  Python's help() function finds this page whenever help() is called
 |  on a ufunc.
 |  
 |  A detailed explanation of ufuncs can be found in the docs for :ref:`ufuncs`.
 |  
 |  **Calling ufuncs:** ``op(*x[, out], where=True, **kwargs)``
 |  
 |  Apply `op` to the arguments `*x` elementwise, broadcasting the arguments.
 |  
 |  The broadcasting rules are:
 |  
 |  * Dimensions of length 1 may be prepended to either array.
 |  * Arrays may be repeated along dimensions of length 1.
 |  
 |  Parameters
 |  ----------
 |  *x : array_like
 |      Input arrays.
 |  out : ndarray, None, or tuple of ndarray and None, optional
 |      Alternate array object(s) in whic

In [36]:
np.info('add')


     *** Found in numpy ***
add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is creat

In [37]:
# [과제] zeros 함수를 이용해서 아래와 같이 출력하세요.
#array(7uyhb)
arr=np.zeros(10)
arr[4]=1
arr

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

In [15]:
# [과제] 인덱싱을 이용하여 아래 배열을 내림차순으로 정렬하세요.
arr=np.array([0,1,2,3,4,5,6,7,8,9])
arr[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [43]:
# [과제] [1,2,0,0,4,0]에서 zero가 아닌 인덱스를 배열 형태로 출력하세요.  , nonzero()
a = np.array([1,2,0,0,4,0])
print(a.nonzero())  #함수 요소중 0이 아닌 값들의 인텍스를 반환해 주는 함수이다.


(array([0, 1, 4], dtype=int64),)


### Fancy Indexing

In [46]:
# Fancy Indexing
arr=np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [47]:
arr[[4,3,0,6]]

array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [50]:
arr[[-3,-5,-7]]

array([[5., 5., 5., 5.],
       [3., 3., 3., 3.],
       [1., 1., 1., 1.]])

In [51]:
arr=np.arange(32).reshape((8,4))
print(arr,'\n')

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]] 



In [57]:
arr[[1,5,7,2],[0,3,1,2]]

array([ 4, 23, 29, 10])

In [68]:
print(arr[[1,5,7,2]],'\n')
print(arr[[1,5,7,2]][:,[0,3,1,2]]) #순서변경

[[ 4  5  6  7]
 [20 21 22 23]
 [28 29 30 31]
 [ 8  9 10 11]] 

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


In [70]:
#배열 전치와 축 바꾸기  (3,5)->(5,3)
arr=np.arange(15).reshape(3,5)
print(arr,'\n')
print(arr.T)   # T전치 벡터 연산에 쓰임

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]] 

[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
