<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#라이브러리-설치" data-toc-modified-id="라이브러리-설치-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>라이브러리 설치</a></span></li><li><span><a href="#스톱워드-제거" data-toc-modified-id="스톱워드-제거-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>스톱워드 제거</a></span></li><li><span><a href="#Stemming-and-Lemmatization" data-toc-modified-id="Stemming-and-Lemmatization-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>Stemming and Lemmatization</a></span></li><li><span><a href="#희소-행렬---COO-형식" data-toc-modified-id="희소-행렬---COO-형식-4"><span class="toc-item-num">4&nbsp;&nbsp;</span>희소 행렬 - COO 형식</a></span></li><li><span><a href="#CSR형식" data-toc-modified-id="CSR형식-5"><span class="toc-item-num">5&nbsp;&nbsp;</span>CSR형식</a></span></li></ul></div>

## 라이브러리 설치

In [1]:
!pip install nltk

In [2]:
from nltk import sent_tokenize
import nltk
nltk.download('punkt')

text_sample = 'The Matrix is everywhere its all around us, here even in this room. \
               You can see it out your window or on your television. \
               You feel it when you go to work, or go to church or pay your taxes.'

sentences =sent_tokenize(text_sample)
sentences 

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\qkrrh\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!


['The Matrix is everywhere its all around us, here even in this room.',
 'You can see it out your window or on your television.',
 'You feel it when you go to work, or go to church or pay your taxes.']

In [3]:
from nltk import word_tokenize

sentences = 'The Matrix is everywhere its all around us, here even in this room.'
word=word_tokenize(sentences)
word

['The',
 'Matrix',
 'is',
 'everywhere',
 'its',
 'all',
 'around',
 'us',
 ',',
 'here',
 'even',
 'in',
 'this',
 'room',
 '.']

In [4]:
from nltk import sent_tokenize
def tokenize_text(text):
    sentences=sent_tokenize(text)
    word=[word_tokenize(sentence) for sentence in sentences]
    return word
token=tokenize_text(text_sample)

In [5]:
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\qkrrh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\stopwords.zip.


True

In [6]:
len(nltk.corpus.stopwords.words('english'))

179

In [7]:
nltk.corpus.stopwords.words('english')

['i',
 'me',
 'my',
 'myself',
 'we',
 'our',
 'ours',
 'ourselves',
 'you',
 "you're",
 "you've",
 "you'll",
 "you'd",
 'your',
 'yours',
 'yourself',
 'yourselves',
 'he',
 'him',
 'his',
 'himself',
 'she',
 "she's",
 'her',
 'hers',
 'herself',
 'it',
 "it's",
 'its',
 'itself',
 'they',
 'them',
 'their',
 'theirs',
 'themselves',
 'what',
 'which',
 'who',
 'whom',
 'this',
 'that',
 "that'll",
 'these',
 'those',
 'am',
 'is',
 'are',
 'was',
 'were',
 'be',
 'been',
 'being',
 'have',
 'has',
 'had',
 'having',
 'do',
 'does',
 'did',
 'doing',
 'a',
 'an',
 'the',
 'and',
 'but',
 'if',
 'or',
 'because',
 'as',
 'until',
 'while',
 'of',
 'at',
 'by',
 'for',
 'with',
 'about',
 'against',
 'between',
 'into',
 'through',
 'during',
 'before',
 'after',
 'above',
 'below',
 'to',
 'from',
 'up',
 'down',
 'in',
 'out',
 'on',
 'off',
 'over',
 'under',
 'again',
 'further',
 'then',
 'once',
 'here',
 'there',
 'when',
 'where',
 'why',
 'how',
 'all',
 'any',
 'both',
 'each

## 스톱워드 제거

In [8]:
print(token)

[['The', 'Matrix', 'is', 'everywhere', 'its', 'all', 'around', 'us', ',', 'here', 'even', 'in', 'this', 'room', '.'], ['You', 'can', 'see', 'it', 'out', 'your', 'window', 'or', 'on', 'your', 'television', '.'], ['You', 'feel', 'it', 'when', 'you', 'go', 'to', 'work', ',', 'or', 'go', 'to', 'church', 'or', 'pay', 'your', 'taxes', '.']]


In [9]:
import nltk

stopwords = nltk.corpus.stopwords.words('english')
result1 = []
for sentence in token:
    result2 = []
    for word in sentence:
        word=word.lower()
        if word not in stopwords:
            result2.append(word)
    result1.append(result2)
result1
    

[['matrix', 'everywhere', 'around', 'us', ',', 'even', 'room', '.'],
 ['see', 'window', 'television', '.'],
 ['feel', 'go', 'work', ',', 'go', 'church', 'pay', 'taxes', '.']]

## Stemming and Lemmatization

In [10]:
from nltk.stem import LancasterStemmer
stemmer = LancasterStemmer()

print(stemmer.stem('Working'),stemmer.stem('Work'),stemmer.stem('Worked'))
print(stemmer.stem('amusing'),stemmer.stem('amuses'),stemmer.stem('amused'))
print(stemmer.stem('happier'),stemmer.stem('happiest'),stemmer.stem('happy'))
print(stemmer.stem('fancy'),stemmer.stem('fancier'),stemmer.stem('fanciest'))

work work work
amus amus amus
happy happiest happy
fant fant fanciest


In [13]:
from nltk.stem import WordNetLemmatizer
import nltk
nltk.download('wordnet')
nltk.download('omw-1.4')

lemma=WordNetLemmatizer()
print(lemma.lemmatize('amusing','v'),lemma.lemmatize('amuses','v'),lemma.lemmatize('amused','v'))
print(lemma.lemmatize('happier','a'),lemma.lemmatize('happiest','a'),lemma.lemmatize('happy','a'))
print(lemma.lemmatize('fancy','a'),lemma.lemmatize('fancier','a'),lemma.lemmatize('fanciest','a'))


[nltk_data] Downloading package wordnet to
[nltk_data]     C:\Users\qkrrh\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping corpora\wordnet.zip.
[nltk_data] Downloading package omw-1.4 to
[nltk_data]     C:\Users\qkrrh\AppData\Roaming\nltk_data...
[nltk_data]   Package omw-1.4 is already up-to-date!


amuse amuse amuse
happy happy happy
fancy fancy fancy


## 희소 행렬 - COO 형식

In [14]:
from scipy import sparse

dense2 = np.array([[0,0,1,0,0,5],
             [1,4,0,3,2,5],
             [0,6,0,3,0,0],
             [2,0,0,0,0,0],
             [0,0,0,7,0,8],
             [1,0,0,0,0,0]])
# 0이 아닌 데이터 추출
data2 = np.array([1,5,1,4,3,2,5,6,3,2,7,8,1])

row_pos = [0,0,1,1,1,1,1,2,2,3,4,4,5]
col_pos = [2,5,0,1,3,4,5,1,3,0,3,5,0]

sparse_coo=sparse.coo_matrix((data2,(row_pos,col_pos)))
print(sparse_coo)
sparse_coo.toarray()

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1


array([[0, 0, 1, 0, 0, 5],
       [1, 4, 0, 3, 2, 5],
       [0, 6, 0, 3, 0, 0],
       [2, 0, 0, 0, 0, 0],
       [0, 0, 0, 7, 0, 8],
       [1, 0, 0, 0, 0, 0]])

## CSR형식

In [15]:
ros_pos_ind=np.array([0,2,7,9,10,12,13]) #마지막 값의 길이
sparse_csr = sparse.csr_matrix((data2,col_pos,ros_pos_ind))
print(sparse_csr)
print(sparse_csr.toarray())

  (0, 2)	1
  (0, 5)	5
  (1, 0)	1
  (1, 1)	4
  (1, 3)	3
  (1, 4)	2
  (1, 5)	5
  (2, 1)	6
  (2, 3)	3
  (3, 0)	2
  (4, 3)	7
  (4, 5)	8
  (5, 0)	1
[[0 0 1 0 0 5]
 [1 4 0 3 2 5]
 [0 6 0 3 0 0]
 [2 0 0 0 0 0]
 [0 0 0 7 0 8]
 [1 0 0 0 0 0]]
