<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Numpy-Review" data-toc-modified-id="Numpy-Review-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Numpy Review</a></span><ul class="toc-item"><li><span><a href="#reshape()" data-toc-modified-id="reshape()-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>reshape()</a></span></li><li><span><a href="#Indexing" data-toc-modified-id="Indexing-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>Indexing</a></span></li><li><span><a href="#Slicing" data-toc-modified-id="Slicing-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Slicing</a></span></li><li><span><a href="#Fancy-Indexing" data-toc-modified-id="Fancy-Indexing-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Fancy Indexing</a></span></li><li><span><a href="#Boolean-Indexing" data-toc-modified-id="Boolean-Indexing-1.5"><span class="toc-item-num">1.5&nbsp;&nbsp;</span>Boolean Indexing</a></span></li><li><span><a href="#Sort" data-toc-modified-id="Sort-1.6"><span class="toc-item-num">1.6&nbsp;&nbsp;</span>Sort</a></span></li></ul></li></ul></div>

In [1]:
import numpy as np

## Numpy Review

In [9]:
array1 = np.array([1, 2, 3])
array2 = np.array([[1, 2, 3],
                   [2, 3, 4]])
array3 = np.array([[[1, 2, 3]]])
print(array1, type(array1), array1.shape)
print(array2, type(array2), array2.shape)
print(array3, type(array3), array3.shape)

[1 2 3] <class 'numpy.ndarray'> (3,)
[[1 2 3]
 [2 3 4]] <class 'numpy.ndarray'> (2, 3)
[[[1 2 3]]] <class 'numpy.ndarray'> (1, 1, 3)


In [21]:
array_int = np.array([1, 2, 3])
array_float = array_int.astype('float64')
print(array_float.dtype)
array_int2 = array_float.astype('int')
print(array_int2.dtype)

float64
int32


In [25]:
zero_array = np.zeros((3, 2), dtype='int32')  # 새성시 dtype 설정
print(zero_array)

[[0 0]
 [0 0]
 [0 0]]


In [29]:
one_array = np.ones((3, 2), dtype='int64')
print(one_array)

[[1 1]
 [1 1]
 [1 1]]


### reshape()

In [32]:
ar1 = np.arange(10)
print(ar1, ar1.shape)
ar2 = ar1.reshape(2, 5)
print(ar2, ar2.shape)
ar3 = ar1.reshape(1, 2, 5)
print(ar3, ar3.shape)

[0 1 2 3 4 5 6 7 8 9] (10,)
[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[[0 1 2 3 4]
  [5 6 7 8 9]]] (1, 2, 5)


In [36]:
ar2 = ar2.reshape(2, -1)
print(ar2, ar2.shape)
ar3 = ar1.reshape(1, 2, -1)
print(ar3, ar3.shape)

[[0 1 2 3 4]
 [5 6 7 8 9]] (2, 5)
[[[0 1 2 3 4]
  [5 6 7 8 9]]] (1, 2, 5)


In [43]:
# 3차원을 2,1차원으로
ar3 = np.arange(8).reshape((2, 2, 2))
print(ar3, ar3.shape)
ar2 = ar3.reshape(4, 2)
print(ar2, ar2.shape)
ar1 = ar3.reshape(-1)
print(ar1, ar1.shape)

[[[0 1]
  [2 3]]

 [[4 5]
  [6 7]]] (2, 2, 2)
[[0 1]
 [2 3]
 [4 5]
 [6 7]] (4, 2)
[0 1 2 3 4 5 6 7] (8,)


### Indexing

In [48]:
ar1 = np.arange(1, 10)
print(ar1)
value = ar1[1]
print(value)
value = ar1[-1]
print(value)
value = ar1[-3]
print(value)

[1 2 3 4 5 6 7 8 9]
2
9
7


In [55]:
ar2d = np.arange(1, 10).reshape(3, 3)
print(ar2d)
print(ar2d[0, 0])
print(ar2d[0, 1])
print(ar2d[1, 0])
print(ar2d[2, 2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
1
2
4
9


### Slicing

In [60]:
ar1 = np.arange(1, 20)
print(ar1)
print(ar1[3:6])
print(ar1[-4:-1])

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[4 5 6]
[16 17 18]


In [75]:
ar2d = np.arange(1, 10).reshape(3, 3)
print(ar2d)
print(ar2d[:2, :2])
print(ar2d[1:, :])
print(ar2d[:2, 1:])
print(ar2d[:2, :1].reshape(-1))
print(ar2d[:2, 0])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1 2]
 [4 5]]
[[4 5 6]
 [7 8 9]]
[[2 3]
 [5 6]]
[1 4]
[1 4]


### Fancy Indexing

In [94]:
ar2 = np.arange(1, 10).reshape(3, 3)
print(ar2[[0, 1], 2])
print(ar2[[0, 1], :2])
print(ar2[[0, 1]])

[3 6]
[[1 2]
 [4 5]]
[[1 2 3]
 [4 5 6]]


### Boolean Indexing

In [79]:
ar1 = np.arange(1, 10)
print(ar1)
ar1[5:]

[1 2 3 4 5 6 7 8 9]


array([6, 7, 8, 9])

### Sort

In [100]:
# np.sort -> 원본에 반영되지 않음
ar = np.array([3, 1, 9, 5])
print(ar)
sort_ar = np.sort(ar)
print(sort_ar)
print(ar)
sort_ar1 = ar.sort()
print(sort_ar1)
print(ar)

[3 1 9 5]
[1 3 5 9]
[3 1 9 5]
None
[1 3 5 9]


In [102]:
sort_ar_desc = np.sort(ar)[::-1]
print(sort_ar_desc)

[9 5 3 1]


In [108]:
ar2 = np.array([[8, 12],
               [7, 1]])
print(ar2)
sort_ar2_axis0 = np.sort(ar2, axis=0)
print(sort_ar2_axis0)
sort_ar2_axis1 = np.sort(ar2, axis=1)
print(sort_ar2_axis1)

[[ 8 12]
 [ 7  1]]
[[ 7  1]
 [ 8 12]]
[[ 8 12]
 [ 1  7]]


In [110]:
# 정렬 행렬의 인덱스 반환
ar = np.array([3, 1, 9, 5])
print(ar)
sort_indices = np.argsort(ar)
print(sort_indices)

[3 1 9 5]
[1 0 3 2]


In [112]:
# 행렬 내적
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8], [9, 10], [11, 12]])
np.dot(a, b)

array([[ 58,  64],
       [139, 154]])

In [117]:
# 전치 행렬
a = np.array([[1,2],[3,4]])
a.T

array([[1, 3],
       [2, 4]])