<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#판다스" data-toc-modified-id="판다스-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>판다스</a></span></li><li><span><a href="#데이터프레임" data-toc-modified-id="데이터프레임-2"><span class="toc-item-num">2&nbsp;&nbsp;</span>데이터프레임</a></span></li><li><span><a href="#pands-indexing" data-toc-modified-id="pands-indexing-3"><span class="toc-item-num">3&nbsp;&nbsp;</span>pands indexing</a></span></li></ul></div>

## 판다스
- 판다스는 구조화된 데이터 형식을 제공, 시리즈는 1차원 배열, 데이터프레임은 2차원 배열
- 라이브러리는 여러 종류의 class와 다양한 내장 함수로 구성, 시리즈와 데이터프레임은 대표적인 클래스 객체임
- 시리즈 인덱스는 데이터값과 일대일 대응. 파이썬 딕셔너리와 비슷한 구조. pandas.Series(딕셔너리)
- Contents
 - Series(변환, 인덱스 구조, 원소 선택)
 - DataFrame(변환, 인덱스, 삭제, 선택, 추가, 변경, 전치 등)

In [ ]:
# 딕셔너리를 시리즈로 변환
import pandas as pd
dic_data = {'a':1,'b':2,'c':3}
sr=pd.Series(dic_data)
print(sr,type(sr))

In [11]:
# 리스트를 시리즈로 변환
list=['2019-10-02',3.14,'ABC','100',True]
sr=pd.Series(list,index=['a','b','c','d','e'])
print(sr,type(sr))

a    2019-10-02
b          3.14
c           ABC
d           100
e          True
dtype: object <class 'pandas.core.series.Series'>


In [13]:
idx = sr.index
print(idx)
val = sr.values
print(val)

Index(['a', 'b', 'c', 'd', 'e'], dtype='object')
['2019-10-02' 3.14 'ABC' '100' True]


In [16]:
#튜플 시리즈로 변환
tup_data=('영인','2015-15-01','여',True)
sr=pd.Series(tup_data,index=['이름','생년월일','성별','학생여부'])
print(sr)

이름              영인
생년월일    2015-15-01
성별               여
학생여부          True
dtype: object


In [26]:
print(sr['이름'])
print(sr['생년월일'])
print(sr[1:3])
print(sr[[1,3]])

영인
2015-15-01
생년월일    2015-15-01
성별               여
dtype: object
생년월일    2015-15-01
학생여부          True
dtype: object


In [36]:
#배열을 시리즈로 변환
import numpy as np
s1 = np.arange(start=11,stop=16)
s2 = pd.Series(s1,index=['ED1','ED2','ED3','ED4','ED5'])
print(s1,type(s1),'\n')
print(s2,type(s2))

[11 12 13 14 15] <class 'numpy.ndarray'> 

ED1    11
ED2    12
ED3    13
ED4    14
ED5    15
dtype: int32 <class 'pandas.core.series.Series'>


In [32]:
print(s2[1:3])
print(s2[[1,3]])

ED2    12
ED3    13
dtype: int32
ED2    12
ED4    14
dtype: int32


In [41]:
# 시리즈 -> 배열
print(type(s2))
ar=np.array(s2)
print(type(ar))


<class 'pandas.core.series.Series'>
<class 'numpy.ndarray'>


In [ ]:
class numpy as np
np.ar

In [4]:
# 4가지 자료형 데이터를 생성하고 각각 Series로 변환하여 출력하세요.
import numpy as np
import pandas as pd
listt = [1,2,3,4,5]
tuple = (1,2,3,4,5)
dic = {1:'하나',2:'둘',3:'셋'}
arr = np.array([1,2,3,4])
sr1=pd.Series(list)
sr2=pd.Series(tuple)
sr3=pd.Series(dic)
sr4=pd.Series(arr)
print(sr1,sr2,sr3,sr4)


0    <class 'list'>
dtype: object 0    1
1    2
2    3
3    4
4    5
dtype: int64 1    하나
2     둘
3     셋
dtype: object 0    1
1    2
2    3
3    4
dtype: int32


In [6]:
lidata = [2,3,4,5]
tudata = (True,False,True,True)
dicdata = {'김첨지':'설렁탕','점순이':'감자','나':'아달린'}
arrdata = np.array(['살바도르','빈센트','파블로','램브란트'])
index = ['1번','2번','3번','4번']

li = pd.Series(lidata,index)
tu = pd.Series(tudata,index)
dic = pd.Series(dicdata)
arr = pd.Series(arrdata,index)

print(li,'\n',tu,'\n',dic,'\n',arr)


1번    2
2번    3
3번    4
4번    5
dtype: int64 
 1번     True
2번    False
3번     True
4번     True
dtype: bool 
 김첨지    설렁탕
점순이     감자
나      아달린
dtype: object 
 1번    살바도르
2번     빈센트
3번     파블로
4번    램브란트
dtype: object


In [12]:
data=np.arange(1000,5000,1000)
obj=pd.Series(data)
state=['Califonia','Ohio','Oregon','Texas']
obj.name = 'population'
obj.index= state
obj.index.name='state'
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Name: population, dtype: int32

In [16]:
obj['Newyork'] = 3000

In [17]:
obj

state
Califonia    1000
Ohio         2000
Oregon       3000
Texas        4000
Newyork      3000
Name: population, dtype: int64

In [18]:
obj.Newyork

3000

In [4]:
obj.Califonia = np.nan
obj

state
Califonia       NaN
Ohio         2000.0
Oregon       3000.0
Texas        4000.0
Name: population, dtype: float64

In [7]:
obj.isnull()

state
Califonia     True
Ohio         False
Oregon       False
Texas        False
Name: population, dtype: bool

In [8]:
obj.isnull().sum()

1

## 데이터프레임
- 데이터프레임은 2차원 배열, R의 데이터프레임에서 유래
- 데이터프레임의 열은 각각 시리즈 객체
- 시리즈를 열벡터하고 하면 데이터프레임은 여러개의 열벡터들이 같은 행 인덱스를 기준으로 줄지어 결합된 2차원 벡터 또는 행렬
- 선형대수학에서 열 벡터(mx1행렬)는 m 원소들의 단일 열 행렬
- 행 벡터(1xm 행렬)은 m원소들의 단일 행 행렬
- 리스트, 딕셔너리, 배열 등 다양한 데이터로부터 생성
- 반대로 리스트, 딕셔너리, 배열 등으로 변환될 수 있음

In [5]:
#배열->데이터프레임
ar= np.random.randint(100,120,size=(3,3))
print(ar,type(ar),'\n')
df=pd.DataFrame(ar,index=['d1','d2','d3'],columns=['pd','sales','int'])
print(df,type(df))
df

[[110 113 103]
 [107 100 100]
 [106 109 108]] <class 'numpy.ndarray'> 

     pd  sales  int
d1  110    113  103
d2  107    100  100
d3  106    109  108 <class 'pandas.core.frame.DataFrame'>


pd  sales  int
d1  110    113  103
d2  107    100  100
d3  106    109  108

## pands indexing
- iloc : integer location의 약자, 데이터프레임의 행이나 칼럼의 순서를 나타내는 정수로 특정 값을 추출해오는 방법
- loc : 인덱스명, 칼럼명을 직접 적어 특정 조건식을 써줌으로써 사람이 읽기 좋은 방법으로 데이터에 접근하는 방법

In [6]:
#행 선택 
print(df.iloc[1],'\n\n') #d2
print(df.loc['d2'])

pd       107
sales    100
int      100
Name: d2, dtype: int32 


pd       107
sales    100
int      100
Name: d2, dtype: int32


In [22]:
# 특정 행, 열 선택
print(df.iloc[1,1],'\n')
print(df.loc['d2','sales'])

115 

115


In [23]:
df.iloc[1,1]=100
print(df.iloc[1,1])

100


In [8]:
# 행, 열 추가
df1 = df.copy()
df1.loc['d5']= 100,200,220
df1.loc[:,'price']=100,200,np.nan,np.nan
df1

pd  sales  int  price
d1  110    113  103  100.0
d2  107    100  100  200.0
d3  106    109  108    NaN
d5  100    200  220    NaN

In [13]:
df1['pf']=[200,300,400,100]
df1
del df1['pf']
df1

pd  sales  int  price
d1  110  113.0  103  100.0
d2  107    NaN  100  200.0
d3  106  109.0  108    NaN
d5  100  200.0  220    NaN

In [9]:
# 원소값 변경
df1.iloc[1,1]=np.nan
df1

pd  sales  int  price
d1  110  113.0  103  100.0
d2  107    NaN  100  200.0
d3  106  109.0  108    NaN
d5  100  200.0  220    NaN

In [47]:
# 사전 -> 데이터프레임
sp1=np.arange(1,6)
df=pd.DataFrame({
    'col1':sp1,
    'col2':sp1*2,
    'col3':['A','B','C','D','E']
})
df

col1  col2 col3
0     1     2    A
1     2     4    B
2     3     6    C
3     4     8    D
4     5    10    E

In [114]:
# 딕셔너리 값이 스칼라이면 인덱스 필요
dic = {'A':1,'B':2,'C':3,'D':4}
columns=['a','b','c','d','e']
index=[1,2,3,4]
df=pd.DataFrame(dic,index)
df

A  B  C  D
1  1  2  3  4
2  1  2  3  4
3  1  2  3  4
4  1  2  3  4

In [49]:
#리스트 -> 데이터프레임
np.random.seed(0)
a=np.random.randint(1,5,size=(10,5))
list1=a.tolist()
list1
index=np.arange(1,11)
df=pd.DataFrame(list1,index,columns=['c1','c2','c3','c4','c5'])
df

c1  c2  c3  c4  c5
1    1   4   2   1   4
2    4   4   4   2   4
3    2   3   1   4   3
4    1   1   1   3   2
5    3   4   4   3   1
6    2   2   2   2   1
7    2   1   4   1   4
8    2   3   4   4   1
9    3   4   1   2   4
10   2   4   4   3   4

In [59]:
#데이터프레임 -> 배열, 리스트, 딕셔너리
ar=df.values
print(ar,ar.dtype,'\n')
il=df.values.tolist()
print(il)
print()
dict = df.to_dict('list')
print(dict)

[[1 4 2 1 4]
 [4 4 4 2 4]
 [2 3 1 4 3]
 [1 1 1 3 2]
 [3 4 4 3 1]
 [2 2 2 2 1]
 [2 1 4 1 4]
 [2 3 4 4 1]
 [3 4 1 2 4]
 [2 4 4 3 4]] int64 

[[1, 4, 2, 1, 4], [4, 4, 4, 2, 4], [2, 3, 1, 4, 3], [1, 1, 1, 3, 2], [3, 4, 4, 3, 1], [2, 2, 2, 2, 1], [2, 1, 4, 1, 4], [2, 3, 4, 4, 1], [3, 4, 1, 2, 4], [2, 4, 4, 3, 4]]

{'c1': [1, 4, 2, 1, 3, 2, 2, 2, 3, 2], 'c2': [4, 4, 3, 1, 4, 2, 1, 3, 4, 4], 'c3': [2, 4, 1, 1, 4, 2, 4, 4, 1, 4], 'c4': [1, 2, 4, 3, 3, 2, 1, 4, 2, 3], 'c5': [4, 4, 3, 2, 1, 1, 4, 1, 4, 4]}


In [130]:
# 배열, 리스트 ,딕셔너리로 데이터프레임을 생성한후 다시 배열, 리스드, 딕셔너리로 변환하여 출력
ar=np.arange(25).reshape(5,5)
df1 = pd.DataFrame(ar,index=['a','b','c','d','e'],columns=['a','b','c','d','e'])
print(df1)
print(df.values) #배열
a=np.random.randint(1,5,size=(5,5))
list1=a.tolist()
df2 = pd.DataFrame(list1,columns=['a','b','c','d','e'])
print(df2)
print(df.values.tolist())
dico={'A':[1,2,3,4,5],
    'B':[1,2,3,4,5],
    'C':[0,1,2,3,6]}
df3=pd.DataFrame(dico)
print(df3)
print(df3.to_dict('list'))

    a   b   c   d   e
a   0   1   2   3   4
b   5   6   7   8   9
c  10  11  12  13  14
d  15  16  17  18  19
e  20  21  22  23  24
[[1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]
 [1 2 3 4]]
   a  b  c  d  e
0  1  3  1  4  2
1  3  1  3  4  1
2  1  2  1  2  1
3  3  4  4  1  3
4  2  4  4  1  3
[[1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4], [1, 2, 3, 4]]
   A  B  C
0  1  1  0
1  2  2  1
2  3  3  2
3  4  4  3
4  5  5  6
{'A': [1, 2, 3, 4, 5], 'B': [1, 2, 3, 4, 5], 'C': [0, 1, 2, 3, 6]}


In [99]:
# 리스트
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'],columns=['Food'])
print(df1,'\n')
print(df1.values.tolist(),type(df1.values.tolist()),'\n')

# 딕셔너리
df2 = pd.DataFrame({
    '커피':4000,
    '쿠키':3000,
    '케이크':6500
},index=['가격'])
print(df2,'\n')
print(df2.to_dict('list'),type(df2.to_dict('list')),'\n')

# 배열
df3 = pd.DataFrame(np.random.randint(1,10,size=(3,3)),index=['1반','2반','3반'],
                   columns=['달리기','줄다리기','무궁화'])
print(df3,'\n')
print(df3.values)


     Food
메뉴1    냉면
메뉴2   칼국수
메뉴3  잔치국수
메뉴4   수제비
메뉴5    우동 

[['냉면'], ['칼국수'], ['잔치국수'], ['수제비'], ['우동']] <class 'list'> 

      커피    쿠키   케이크
가격  4000  3000  6500 

{'커피': [4000], '쿠키': [3000], '케이크': [6500]} <class 'dict'> 

    달리기  줄다리기  무궁화
1반    7     2    7
2반    8     3    4
3반    2     6    3 

[[7 2 7]
 [8 3 4]
 [2 6 3]]


In [112]:
#file 생성
li = ['냉면','칼국수','잔치국수','수제비','우동']
df1 = pd.DataFrame(li,index=['메뉴1','메뉴2','메뉴3','메뉴4','메뉴5'],columns=['Food'])
df1.to_csv("./dataset/file_data.csv",index=None)
file_data = pd.read_csv("./dataset/file_data.csv")

file_data


Food
0    냉면
1   칼국수
2  잔치국수
3   수제비
4    우동